  

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: "{cipher}c43d3acc08d5895a361cb9ceee69b371718f1c1f3b20c1ee7721cb682f00af7c"
  cloud:
    gateway:
      routes:
        - id: rest-service
          uri: http://localhost:19090
          predicates:
            - Path=/rest/**
        - id: test-service
          uri: http://localhost:19090
          predicates:
            - Path=/test/**
