reffics-config:
  name: default update test test cipher

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: "{cipher}daa6c42e919aae87206742c494b1b2089bf45557902179cca354644672767792"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true